language: node_js
node_js:
- 12
sudo: false
cache:
  yarn: true
  directories:
  - node_modules
install:
- yarn global add serverless
- yarn
jobs:
  include:
  - stage: test
    script: yarn test
  - stage: deploy
    script: sls deploy -s product
env:
  global:
  - secure: M+m5f2bK62WSNfgqOOcPKDNuDAtyqXsENR2Td7LUxTacYAYZEVm54/MFOJncHnr8bIfojbjr5OjEDKqs9N3eDWtvI9MhElzv0viRIyz5Ni3XxX2NfWNTAuodwIMlJHQNRsMOTFi1BgXEAU4dUtMxrnNf5hBlO9983y8Od9vvj1469LnLcUCZJKICT1s4k/H/U2HniqYcaNFG2G5LWkSoyvaJP2QO6gTDRVElGyHkUG7YpADHApY/hxRisiZUN6hkVoExpxWkMbV6h82gtzBpglnPimLzJO04EnTFfPh4qxvIJxggCd7zvpRDpOj8yOXnoeO8P6Evd94KMxpCY2sQct+0lqcAc4eTgLUlpXv8M1+8PcFu3TaE1vYT7OmfGS5vYCJ02Rf11cA5IxVsrflnSkj789A0o+nzNPevovQlGSWKT94s2cs3N+TKDAfbOFkYTCRxO3r/oY0Dv+4f2tz6+XHnJJodQvAfX/29IimxUB0VwFsL5VSXoHSSLc8OdIho856cRznTlhU5TrM74D10SxIFWU6+XTaref1MXxofD2UnrF9S93BdMuPZyxfEQDBp37zsd02qt1vAZBtJUKEiJreFFxGkCqRJKM2cec/tNdMETvK8P5ChF81g2uelGOPyHGULbZzIW6W7y6HNON0ocaILxWpXpSoIUarOkI600EE=
  - secure: cdEtkitLVhMXFpou23Goznt3lT/TxVZWSbPpBYqDfR7EDPlc9DGTdBLu51RnunLp32tb8oD3c+0npJ4LQQfX7dU9I6K1tkzqc/czSm0KNMnRou4hjHRIR4ZpFDYYYb40sGcikoHKnjZhQrwHTk2ONT3UtOa/Q0ORebqKiYIay0Oe2uphftaf58OQ7MTnIrXtNUPYtle3nWyXrxZE1XH0XK71oISeMIlHNyAYbjiQ4231v2W+EICotZGkQlxScufgqXYMAD+TlHpnU5hd0vPiZ/C52IBOKtTaSvilWDzXVGInmzyScUbkajA4nfQLhNG91EgoPkri0d+Vf/yS7I8phSWC5xi6cDdaYzMpiUaoCmo3UkDf7OdTGNBCJWT+BrL7YIqifLaZ/xoMyJ/S+FG5QP9YstC/QYyzLF//Fp/uP0F9Utw56RnGwZ/QdBZlJcv2r/q8pqyyD0CXSWSsEYtpqO1SMy6bKUWkUgZqPif7pZtvNRlP1hgTg2G55y0ZpWG1j2U2AC0FfNEBdtfYau0RLJYed07fAb8QHOJuDbl2T9UQ5U85Akzf+DMEe8JN6WSHx6xao0ZQPwE5+mv88oR44QvqdVqMmtddiveodIyjhBJkRwP+EGWO1V8noQ/OxewIoihdGF0GPkYSqbtuCgDyApo1ljsMFlySTVGxQstoKA8=
  - secure: UeffjX6XoS07IkSbN04E4gMT3wO9jfZiDsqU/AusfQlvNaI6GgydXqyydfGgV8zUO9jjRHmWNlYB1TiM18AgW585ZYlryN5g2MCd97pHTZ5iLjPIOByo75WUW5+8C3nWrB/EMnWMfAQl9Unskvjb+o/OoE7BLxLc252Mh2VZdYkoWFgAsbM6s9Xp1TNYwLotbuEBpfLxGxbLlCy73A7W353BUrksXCCjLq9VlA9+UPMCExrJkdZ9pZdrxCwdvZpNwUZF4KQqGjsXhfv1oEUFPwVijIeHdcyh44acJeKHySgXhsoipPP6ErvqeJAiy9ITAEQTNFeazbVz2nRTkDkEM9cs7LwWp1yiK/dUi9hbaJdTeTeCWYoYq/La1st9qDp+yaz+PySCVtrGPJIvdZE/P+t8svlS7Ozjpw1MBq9H8ghdZa3HdOt1vbVJozn7KQ5Q6Zmh51OD4IeTKf/hDVAf+jCFDUUVZ8J5qhCprQLYKbPfldYwuLmhQ79mbT7b5Ze8aDSKo7yB7yX21GA18B3GNHTYzHuAXMdgqi+WlR2g10ag29TBg9nZ6AcbuUTdPlzztJsjLxjNmIUFYFbP0E0/oPgV3JWMED4A6m7TAuSsUtOBP2Z/whrqf4aOl1EJU/1Fl+UJ987jO20SWzcI+Xgou8fPFP/hJuAh9angtQ3M+0I=
