language: node_js
node_js:
- 12
sudo: false
cache:
  yarn: true
  directories:
  - node_modules
install:
- yarn global add serverless
- yarn
jobs:
  include:
  - stage: test
    script: yarn test
  - stage: deploy
    script: sls deploy -s product
env:
  global:
  - secure: Rpz02HeGu7Iz5e20ZWYSICPPAtOR4ptWK/w7J+Ys3z8MYdRhB/W3nWbHUNjNSb5GwL1ebic7KO6zwOaQpGa46or7Mhte0qdLzNU0Loco8X5Q169BLCMS+CB7HLLrnH3Vn1iS5OmeJDBC722wkJ/hxfvLPd8iZczkvRk7fDZMhM1ibetVf1CNcutiMJpV7yMGawF1sMQLC0k5juEFANxnH+rOAFK1Dfs2Z1MogGmL8Kk28BXtIn9ICJQyc0MriKHP+O9Zz5pL4BrpU2TFzbPWrOhJoOjakehqHhPD2tQrp8E+VweWicMEQhVlU9soNSSIxiuIt1CYBahhpdLDumyarT3reebbbCnrvVIM7SKEcrgAhW4rtB4HzQS6Wb6Yk6sgN1Zqu39/iDlVFDclcizcTRkN+eCX9wKCODIWSfDUzHAttKl0is8Ig8zbCuv6qKz4L2KodMnffL+C9UcujciiAPnZvvxaavxlrDECas/ul8w/NX3P0AxW638JSjU5T6mPikMyR51yXQrv8ae9e1i2Iqco2dlZ9aJRBYChfPiNsJWBB3s6Hvv8ADigejCLJpLBuFffMaS+tZctPBF3nZYMx07LxaUGgySZpYHWGNkqibWxUxS5Q9Qu/4nvrMBwMeOqDv8PJ73CQDPnbOeNP50vav8ApB/DKleqlXXfqU9cQ4g=
  - secure: Mu8OStN8xSm0glqIlo21vf2HZkO3diQkEzaqmy7hKKJEn3f91GQ30bdLgpcovCUHPhJCWH4vzLhUOpj7o1a7qsT7cKn3sAgQy2Fny9GHMe/zwx7T1NMOB9XRTmk6rdqr149c84sbLqGRa9GGD981/HQLRTUvceFf+PiEe3OxRCxYwM193uAxeaxPMVRr0zHj2vTKJ4Ci6DCdX0aPnOwbjixS8MIQ+oOLRnYbaFJhA9IfzzXp7ibJ4iBjnxSY586jw9e8Jut0LcMGvmEEfPVtNjKKKWf0yB/bJHyLTJZJI+U4NLC3khFC3kc1kD73qFLPZu99WudCvHukT9m/pV5Wq8mYRgKVAyi62GzRIURGxet09wTS5d22H/l2MWbk+YIwZQNiuPyUIAmWpKaOFZgsiVHcDzC8624dCsq8reuOP8wCYVxmxn8BfiP4K6ydJHVZ7vzomgq4kmzdxFfz6rlKDrskZtzqUrcusJagJUM9TB4xI/7JvAQZSDpR4DihwowJAx8F/GsviIoazYU7ZxUHZGxfGH1pFb385hw/BCzJzNQ2hDfaRqFIGDsowqigtj/0cXQrjPlpc20aM3Tup+ipWMHAfpKByLJFrV2qCK5jKzqH6uDoX3qHUMGKIln84LqTE+3ujXjx8Zb0IXJxmmklg8FsDnZXw6rgIfQ1CRm6l/w=
  - secure: YHKWyE7mV/zxfRNBJl8lp0VmNiuQln6n5Cqiztzt/ZD+EiJdUVSN9zZh8vwBkqgmg0Mhj0mWmBGXoRQPwIlfWCfda80rwc/1uqbFYkRrHmAJARHRwQG+zU3tZOZ6bhRIDL/ZpZtmDjbOCF3c1AET96arM7JMciQzI1X/p1LtiMP4LkJ/riyrYwRa5sOIpBZHBthVDLtHN7O+0erWqVyZbhXEzzS2bpqL5OIiHGxF+A0MkICn2NoH3VlIXdLg4SR5bFWb76uIonhpuYE4h6Dw0pldwMdBpEsjrMG0/2uba4/2KvfHZ16C44BQcUAWn0K2hVheC1n6Uj4zEeW08h8JplT5FJuJkPrdZBLCvI2Z3LbF53kqOEDM7jRLF2duTwfqkvWs1dgaEqiMvFpJb4KxgRZIZoTIzqefHqwnrCMmWQmeShpl7nftRCJr6NwfcUg6zuYeL2DN2R5TltxSkaZRWre5ITDPH3XXX63B5TeGdFrmVdZtzoxNoh0ppiVEw7ZPWLgmj77HcwPpHxWUkkegcxcmasCKQdyK5pVih0c11AaqeM3IzA0i49iKQo2gUACBaV/XpxAdOKb0tkN/S745XoStCYfwsl/j38VPogWFaHnRRQ4mR3I/6hPEVkU+CjhEExA7+5/gf4ASfHSDa51MIL5QlhcLfHwNJAXsnKv+znM=
