language: node_js
node_js:
- 12
sudo: false
cache:
  yarn: true
  directories:
  - node_modules
install:
- yarn global add serverless
- yarn
jobs:
  include:
  - stage: test
    script: yarn test
  - stage: deploy
    script: sls deploy -s product
env:
  global:
  - secure: dEM0lsy81MMUEm7XN/TkPpgLV19GG3ccYNs+/bYrVIdujz6/fv5IYzmCiISHqhl5xMWhwu+Cm4vt6EJK4OlcE1caFQMUanC8V3IK0aEaMOAAbQUWQNugKGmVxUsYa4eVmRvH5NiFXQeXUiEek6wB/M0YxAWbjjOOiBXOhyhi61j0eOFkk4Y4tswROMs9Ek383C72DtXwDYGjSUf1KQLe803xI/5Lvx6AeFi+J8zE1qSKAK6Rnf2W5bDE/zHoLuIvJTKzjNr6kM9Og7719JYwcRBAPp0carwKZnIwNfdp69u/dgF0aoABUguDg30zdTEfmM1k0sh17hmYARbtJq4TR9skS5F8hMG2Jy6N2UqNTjGB2/U2f0yEPDz9jOfqSA4tYp/o9K3XlP9NW7wvb2on4fpGPkcLwG3H6muzeowHsYPpUCARHaWO64FF1+V+hMCMqCsl0t+DzJ8/GNeKTE96yyRyhcpF8BF+uTDXdwFjEqiqz1qQH64gA5sezUtzqn9iRVG/1jw7IttXoAGdopMG643lRJUfs52fgAoNzhyldMs6Lepl1Mpw3NThA8ygQQmFQpEtpj3kooWTXoAqJN4rKd6FdQy6TAHxq3UJ53GrnIMByKgSZx15UfLFzlRIOiagfDb26mIQ2E0cbqw6foPywH+oNWb6LyAvew+BoDsq/vk=
  - secure: c/nUwCIdETuaxJdoXUgsxVOjEuUK7nwlVAkkseKToPjS8XRsSJqB8BvOwiwxiXLVHtgm9cjcGRfT7dqVOREvrSdqaZPqf/M0BcN/vvHKABfPfs62gkCDKD+TbomQl9VRq6291aue0KhbyBHzhn7ydPOoogt/Lo4SEYFuISmtC1jgyYmNd66BC/vPh6VViKcdkBDuMUHrBMAkblJqC/EK2Llaxrp9exml5kqEvi3JusEj0StW7ulcR1TA1hk1q9w1OfYcffMWqzYybw3vwHslaRX0jJETNEA3TwkXK1ZUEw7WbuBuKVx4eIjePP01GwofLJae9A5XN1kri5CHHXAwRfMO6skRj4P9NEP951y6ATRi77AIPVbrMCnoytKIAk7asH3lGs0sH5NyS4WEwXRCR9zWctJphP7rTTlI4apSZntqTZmVJrhW6x54AeImiIfInEBsusmzN3YzdpfaSVwcZj0YxFxQlW/YRNq/A9VVoL63A7Hs/rdnlXtVyhXU/amG2v/HH7NRyrH6Flasb5sO22rL2UdUHbdNL3MD66YuXgeQAWisF8e+CMKSQN+ZwYiYbFB8YXiC9C01YELZrDB6QPGfRIDurW3D1bUjYUSA+smO6yNAMyvFqeIf17QP1BYCdPfO51UNeQ/56vPG/JG3MOSTAZegPoh3L57M4OxYZHU=
  - secure: LbZ7fX7VLFitoA37d/aO5GdirVrA5TDyPczP59p9Sl24ItQsLV4BQxN8I2DQuzqN2rhWbvY+Ek24rM3wrcGAS1VNfDTfCUtk6f+p6k29ItHO+N3YPOFu26Sjc5l5r8q+3EuixwRuk0arxvLQlKUIX/+dEUoSd/N2lfBEpJcrd2/T20IgdbLwywUju1pqQiyOMudSPsYtGLepzvtImkv92yf1csTQR7mlK+f9LlJVvYnZ8ssVFpGBxbq1c53/GJhEww/eeSYWENC6ZKu9NH3CPSK2A5z230ndhKlevdo4S3j2OuyHjxLiuvSvaCZ2/aB2kCJHBZiiOvOmcC0ujgKaD04mDWQ+LAvAuq7HRyb+o1O2MAgfHybu0jD4/pPGUqkIUo1RTRvhEcPzh5z4Wv6UO6KJ3IuaOHW9aZ77rhDhnQn/KtGYY42zp+CJkfHt3TqcE699olbYlwowTdIDmjoY19pPc2p5QwmWyi+MKB9xSJ7U5nqIYeAmZdaZRGGoEo/wnT3hIeC56KjWTZVUgJQFSLrUcYC2Og+C7qVPoRh7DI5qSx7L2dwK/U5mmE9RkCu/G8dHSa799nie93SA0WxennwH+quR9txsLUemvzFepboLUtSXxJRT0uZjs/mQWXKGt8Na6SV+1sjrm2BuihA1mEZwEXkLQEyQcOvYEjJRQHQ=
