language: node_js

node_js:
  - 12

sudo: false

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn global add serverless
  - yarn

jobs:
  include:
    - stage: test
      script: yarn test
    - stage: deploy
      script: sls deploy -s product
