language: node_js
node_js:
- 12
sudo: false
cache:
  yarn: true
  directories:
  - node_modules
install:
- yarn global add serverless
- yarn
jobs:
  include:
  - stage: test
    script: yarn test
  - stage: deploy
    script: sls deploy -s product
env:
  global:
  - secure: k8IztPZvqdIxTUnis+YIHBLF/F+ATOCoI3XOAVjK/lF3RHqSQqvmyD26jhmcYTww4bmrobr8vDJQVF+fuTMhTMddRTArDWCxNsuf64V9KI51jCYN+2Pxf0hkAN0pkWIfCI8pgJwi5lOn7T+FddOWhv45AQt6kQaH6QQJHHN1aYc8pxzOnqYuc+jj1k/kQPmQCKA2EtQjQ2pgvg8y0l7SNjcNCn9ryP+GG8+ZLe2qzSr4fKTyUCM0OvK0UC4cXxOBWX3jrqGb6jTnYylo58UNAZszIYNUU5iikINYHaqA1llVO4aNmRvOCkx6cFIEcOvTSirYqitfaagnhQjhrMMzEGAWUVyR+f3PWhbW4OzIeOiM67HAuAl6WEkVvglq2H8Pcv/N6PmlrJe4dHVqzmzZlotTtPKwuw+xBW8SNNzh9UfHXqrgj5xOzzk4v84iNc4uWgpqzG8OuMcmGQoqec/B4ASj9cPwWYZ5jg/l82FipcfunrO3a2wHt8vJVCLCakXc3Z7dPAh4z63VFurC9V5vd66eeLEIkVVtpWvuyLymz2rtqV2DUeAkQox2enFTgP/bEbVMi2CVBZWKSgeG8ydmKhYPGtx8eZc3I57aPBa2kf6rsFrBrGjyC53r5+Ou+jybJjJUY0jhumdJ5arxuJDJbhcj1HXECczwMPAN1gR5jW8=
  - secure: KwxO2JelyEGKlGxG3gFg8cK2SKsWhE/M3kjfKtknhzXv+3z5cOXCCA9xmN5gOvAuk4C68D1gAe+L823c2n7Fjb8CQikK/7tZMlUPPps7LqgMLG04GWnWeL4B/1IBA7R1INtJV6RxAnj7/ZOlh8zW/dZ3mBs7knX0eD/xrlAF1MDLtG4PPwaswAC/4FzMvlbMu4v6jnInG6eXAvHHaTw8bquBOEpNWSoCdP/4t61lxWuNzprSjxrY2GceoBYVXSKqiloATSf/gFs7j6u1WFv4egit86XifW3W1mOXB2vnBX5s7NVBEJoWWeb1gpaqKPtmzUFFBAtkusQKxd413A0dnma3tGYgvNENjgW4WbrAGogGMplxMjOjQ/gRFbQnIYmU9vc5EuXcYJERB/nMqMNL1eoiLPHIVaHrTbu2JtuHZqkhyR25tf9QRUiiFK7d9QWKE4Ntq0juo2ZE9rimX6W2yW8ujl5IeHtfyoEFvHnHKdfupHBrhuBBuwAR27ONnC0JkkBx9NC1rQcw1NZcRbJksXY3I8J9bqCCKBSeNX2Izy/mZUWN38TGWJDFTsuh8sakWo6z/ZnAYSWdlZcrMcOv4w1/CCOfG/jUpCodNUYU5ccahLN9hIili2udMOBtck26zZlAtF4upOWVLmIAqCtlXSSp70fTg+x2KgSafZIaRjE=
  - secure: mXt3tU3tFattjQN/bLJrxkolTMAO9YwKDI4qQW9BYa1XhhZRcM0QTq4kEVGBUFJFUn9SBRz+5aRmh7bwzZ37GV6TLCtYm6mLsOqSNOCmhvlmefqnKZYM6NuAbJLjzqoWeNP6gDk5nqu/JggkMB5qoLnnBnRhiihNfTGtphqHc6nvq2sXwzukAyjOPvPiB6WTfsdo2tg/zf7f+qJ2hPEqbLNh+679+uz78lPiX0JdL3wOZrjTkKZIPXNnsZDi98vZJeeHTsu1w+FsNigDnLk99CO4GkhDrPrnlDTGvr+yfo+8hH7XtlYS8+FZjoez/UTFeUQeqe2dDunW3PiFjw98X12+TPfOhYeKqaxVuoG9WLtRvDTDiTtIPGwWIfWcRQ90/5qKNfii6hZr23kbeezF1PJHxuJwLEH4WcMOaNCU6vNHIpzNSFkYTY65REeHbNgsueC6jWp+6OY8nZbzKVT/0cEtILAVAvdZryf4GymVSrOMk37Dt7b6Wuhi/q5w3kF/VQTOD1p8Q3IV2N8BCCUIsnp145LYkxNsByD0xiNXYBoyQEM9yWjoJgq11QZglXeuR4KNLuzLt2NhtwPCHdam08MhfNgDRh+pbxZ70WwzFuqZo6hEeYiGZbAhqVKHU/rwqLemozMiGVGJ7a+wo2OGdYgv0+CCF41oY8gaLK0fexU=
