version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - yarn global add serverless
      - yarn   
  pre_build:
    commands:
      - yarn test
  post_build:
    commands:
      - sls deploy