version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - yarn global add serverless
      - yarn   
  pre_build:
    commands:
      - yarn test
  post_build:
    commands:
      - sls config credentials -p aws -k AWS_KEY -s AWS_SECRET_KEY
      - sls deploy